<?
// Exibe as váriaveis de retorno
// ESSA PORRA VAI MORRER !
echo "Código da transação: " . $tid . "<br>";
echo "Código de resposta da transação: " . $lr . "<br>";
echo "Código de autorização: " . $arp . "<br>";
echo "Valor da transação: " . $price . "<br>";
echo "Identificação do Pedido na Loja: " . $orderid . "<br>";
echo "Campo livre: " . $free . "<br>";
echo "Mensagem da transação: " . $ars . "<br>";
echo "Tipo de Autenticação: " . $authenttype;
echo "Mensagem: " . $msg;
?>